version: '3.3'
services:
  post_db:
    image: mongo:${MONGOVER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:logging
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${PORT}:${PORT}/tcp
    logging:
     driver: "fluentd"
     options:
       fluentd-address: localhost:24224
       tag: service.ui
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:logging
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:logging
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net
volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
  front_net:
